package com.strikete.photon.csv;

public enum CsvCueLevelHeaders {
	TARGET_TYPE,
	TARGET_TYPE_AS_TEXT,
	TARGET_LIST_NUMBER,
	TARGET_ID,
	TARGET_PART_NUMBER,
	CHANNEL,
	PARAMETER_TYPE,
	PARAMETER_TYPE_AS_TEXT,
	LEVEL,
	LEVEL_REFERENCE_TYPE,
	LEVEL_REFERENCE_TYPE_AS_TEXT,
	LEVEL_REFERENCE_LIST_NUMBER,
	LEVEL_REFERENCE_ID,
	FADE_TIME,
	DELAY_TIME,
	MARK_CUE,
	TRACK_TYPE,
	EFFECT
}
